name: Cypress Test

on: push
  

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Cypress
        uses: cypress-io/github-action@v6

      - name: Run Cypress tests
        run: npx cypress run
